import test from 'tape';
import Fastify from 'fastify';
import crypto from 'crypto';
import sinon from 'sinon';
import { z } from 'zod';
import Redis from 'ioredis';

// Shared fake Redis store
const fakeRedisStore = new Map<string, string>();

const WalletChallengeQuery = z.object({
  address: z.string().min(1, 'address is required'),
});

const WalletVerifyBody = z.object({
  address: z.string().min(1),
  challenge: z.string().min(1),
  signature: z.string().min(1),
});

function buildApp() {
  const app = Fastify({ logger: false });
  const redis = new Redis('redis://fake', { lazyConnect: true }); // Will use stubs
  
  app.get<{ Querystring: { address: string } }>('/api/auth/wallet/challenge', async (request, reply) => {
    try {
      const { address } = WalletChallengeQuery.parse(request.query);
      const nonce = crypto.randomBytes(32).toString('hex');
      const challenge = `BettaPay:${address}:${nonce}`;
      const expiresAt = Date.now() + 2 * 60 * 1000;
      await redis.set(`wallet_challenge:${address}`, JSON.stringify({ challenge, expiresAt }), 'PX', 120000);
      return reply.send({ challenge, expiresAt });
    } catch (err) {
      return reply.code(503).send({ error: 'Authentication service unavailable' });
    }
  });

  app.post<{ Body: any }>('/api/auth/wallet/verify', async (request, reply) => {
    try {
      const d = WalletVerifyBody.parse(request.body);
      const storedRaw = await redis.get(`wallet_challenge:${d.address}`);
      if (!storedRaw) {
        return reply.code(400).send({ error: 'Challenge expired or not found' });
      }
      const stored = JSON.parse(storedRaw as string);
      if (Date.now() > stored.expiresAt) {
        await redis.del(`wallet_challenge:${d.address}`);
        return reply.code(400).send({ error: 'Challenge expired' });
      }
      if (stored.challenge !== d.challenge) {
        return reply.code(400).send({ error: 'Invalid challenge' });
      }
      await redis.del(`wallet_challenge:${d.address}`);
      return reply.send({ token: 'mock-token' });
    } catch (err) {
       return reply.code(503).send({ error: 'Authentication service unavailable' });
    }
  });

  return { app, redis };
}

test('Cross-instance wallet challenge flow using Redis', async (t) => {
  fakeRedisStore.clear();

  // Stub Redis globally so both instances share the same Map
  const setStub = sinon.stub(Redis.prototype, 'set').callsFake(async (key, value, mode, duration) => {
    fakeRedisStore.set(key as string, value as string);
    return 'OK';
  });
  const getStub = sinon.stub(Redis.prototype, 'get').callsFake(async (key) => {
    return fakeRedisStore.get(key as string) || null;
  });
  const delStub = sinon.stub(Redis.prototype, 'del').callsFake(async (key) => {
    fakeRedisStore.delete(key as string);
    return 1;
  });

  // "Instance A" generates the challenge
  const { app: instanceA, redis: redisA } = buildApp();
  const address = 'GABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890';
  
  const resA = await instanceA.inject({
    method: 'GET',
    url: '/api/auth/wallet/challenge',
    query: { address }
  });
  
  t.equal(resA.statusCode, 200, 'Instance A returns 200 OK');
  const bodyA = JSON.parse(resA.body);
  t.ok(bodyA.challenge, 'Instance A generates a challenge');
  t.ok(fakeRedisStore.has(`wallet_challenge:${address}`), 'Challenge is stored in shared Redis');

  // "Instance B" verifies the challenge
  const { app: instanceB, redis: redisB } = buildApp();
  
  const resB = await instanceB.inject({
    method: 'POST',
    url: '/api/auth/wallet/verify',
    payload: {
      address,
      challenge: bodyA.challenge,
      signature: 'mock-signature'
    }
  });
  
  t.equal(resB.statusCode, 200, 'Instance B successfully verifies challenge generated by Instance A');
  t.equal(JSON.parse(resB.body).token, 'mock-token', 'Instance B returns token');

  await instanceA.close();
  await instanceB.close();
  redisA.disconnect();
  redisB.disconnect();
  setStub.restore();
  getStub.restore();
  delStub.restore();
  t.end();
});

test('Graceful fallback when Redis is unreachable', async (t) => {
  // Stub Redis to throw an error (unreachable)
  const setStub = sinon.stub(Redis.prototype, 'set').rejects(new Error('Redis connection failed'));
  const getStub = sinon.stub(Redis.prototype, 'get').rejects(new Error('Redis connection failed'));
  
  const { app, redis } = buildApp();
  const address = 'GABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890';
  
  const resGet = await app.inject({
    method: 'GET',
    url: '/api/auth/wallet/challenge',
    query: { address }
  });
  
  t.equal(resGet.statusCode, 503, 'Returns 503 when setting challenge fails');
  
  const resPost = await app.inject({
    method: 'POST',
    url: '/api/auth/wallet/verify',
    payload: { address, challenge: 'fake', signature: 'fake' }
  });
  
  t.equal(resPost.statusCode, 503, 'Returns 503 when getting challenge fails');
  
  await app.close();
  redis.disconnect();
  setStub.restore();
  getStub.restore();
  t.end();
});
